#!/usr/bin/python

import random
import sys

if len(sys.argv) != 3:
    raise RuntimeError("invalid number of arguments")

file_name = sys.argv[1]
file_count = int(sys.argv[2])

with open(file_name,'w') as f: 
    for i in range(file_count):
        x = random.random()
        y = random.random()
        z = random.random()
        f.write(f"{x};{y};{z}\n")
